### ISSUE TITLE
i can’t get past the cd part i can’t find how to run it and have it show up in roon extensions

### ISSUE THREAD

**Issue by Cxsmo-ai** [jtpox/discord-presence-roon#2]
i can’t get past the cd part i can’t find how to run it and have it show up in roon extensions.

**Comment by jtpox** [comment]
You will need to have [NodeJS](https://nodejs.org/en) installed for it to work.

Then, in your terminal, cd to Desktop (or any other folder you want this to be in). Run these commands:
```
> git clone https://github.com/jtpox/discord-presence-roon.git
> cd discord-presence-roon
> npm install
> node .
```
This will start the extension, which will then show up on Roon's extension page.
After that, enable the extension and make sure to change the settings for the extension to meet your needs!

Hope this helps.

**Comment by Pickymarker** [comment]
okay that helps that is different install instructions then on the github page
