### ISSUE TITLE
this discord rpc fork has activity status changing support so it can fix this https://github.com/jtpox/discord-presence-roon/issues/3

### ISSUE THREAD

**Issue by Cxsmo-ai** [jtpox/discord-presence-roon#4]
this discord rpc fork has activity status changing support so it can fix this https://github.com/jtpox/discord-presence-roon/issues/3                                                                                                                  https://github.com/sKiLdUsT/RPC/tree/master

**Comment by jtpox** [comment]
See https://github.com/discordjs/RPC/issues/146
That thread also has the repo you linked as a pull request. It doesn't work. I've also personally tried that repo. Discord just doesn't allow it.
