### ISSUE TITLE
Updating when "zones_changed" is received comes with lots of issues

### ISSUE THREAD

**Issue by NoaHimesaka1873** [jtpox/discord-presence-roon#7]
- It can’t display seek time properly when song’s in loop or when you change seek time manually. (Stuck at 0 or displays wrong time)
- It only displays playing song when you change the now playing song after you launch this program.

All of this happens because it only updated when "zones_changed" data is received. This is inherently stupid because Roon sends this command only when song is changed in normal circumstances. It should also respond to "zones_seek_changed" and initialize it with data from first "Subscribed" command to fix those issues.

**Comment by jtpox** [comment]
Thank you for the report, I have created a new branch [issue7](https://github.com/jtpox/discord-presence-roon/tree/issue7) to try and fix the issue.

The first update has been pushed. Please take a look at it to see if it works for you. If there are any other bugs or issues, please do let me know.

**Comment by jtpox** [comment]
Thank you for the report, I have created a new branch [issue7](https://github.com/jtpox/discord-presence-roon/tree/issue7) to try and fix the issue.

The first update has been pushed. Please take a look at it to see if it works for you. If there are any other bugs or issues, please do let me know.

**Comment by NoaHimesaka1873** [comment]
First issue seems to be fixed correctly. However the second issue still remains. Thank you for swift response and fix attempts!

**Comment by jtpox** [comment]
> First issue seems to be fixed correctly. However the second issue still remains. Thank you for swift response and fix attempts!

No problem! As for the second point, could you explain in more detail what you meant? I apologize I could not understand what you're trying to say.

**Comment by NoaHimesaka1873** [comment]
> > First issue seems to be fixed correctly. However the second issue still remains. Thank you for swift response and fix attempts!
> 
> 
> 
> No problem! As for the second point, could you explain in more detail what you meant? I apologize I could not understand what you're trying to say.

So, when I'm already listening to some song using Roon and launch this program, it will not get data from Roon (and thus no status on Discord) until song change occurs then it gets "zones_changed" update and finally working.

Also, sorry for bad explanation, I'm not native English speaker :(

**Comment by jtpox** [comment]
Thanks for the explanation! The issue should be fixed in the latest commit on branch `issue7`.

If there are any other issues or bugs, please do let me know. If not, I will merge with the main branch if everything works fine for you!

**Comment by NoaHimesaka1873** [comment]
Tested, and it seems to work well! Closing since it's fixed.
